# These are supported funding model platforms

github: [nathija-nimantha] # GitHub Sponsors
patreon: nathija
open_collective: nathija-collective
ko_fi: nathijanimantha
tidelift: npm/your-package-name
community_bridge: your-project-name
liberapay: nathija
issuehunt: nathija
lfx_crowdfunding: your-project-name
polar: nathija
buy_me_a_coffee: nathija
thanks_dev: nathija
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
