# These are supported funding model platforms

github: [nathija-nimantha] # GitHub Sponsors
patreon: # Replace with username
open_collective: # Replace with username
ko_fi: nathija-nimantha
tidelift: # Replace with username
community_bridge: # Replace with username
liberapay: # Replace with username
issuehunt: # Replace with username
lfx_crowdfunding: # Replace with username
polar: # Replace with username
buy_me_a_coffee: nathija-nimantha
thanks_dev: # Replace with username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
